# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
import numpy as np

In [ ]:
A = np.random.randint(1, 10, (3,3))

A


array([[8, 6, 4],
       [3, 6, 5],
       [8, 9, 8]])

In [ ]:
A = A + np.eye(3)

A

array([[9., 6., 4.],
       [3., 7., 5.],
       [8., 9., 9.]])

In [ ]:
np.dot(A, np.array([1,2,3]))

array([33., 32., 53.])

In [ ]:
np.transpose(A)

array([[9., 3., 8.],
       [6., 7., 9.],
       [4., 5., 9.]])

In [ ]:
B = np.linalg.inv(A)

B

array([[ 0.14516129, -0.14516129,  0.01612903],
       [ 0.10483871,  0.39516129, -0.26612903],
       [-0.23387097, -0.26612903,  0.36290323]])

In [ ]:
A@B

array([[ 1.00000000e+00, -2.22044605e-16,  0.00000000e+00],
       [ 1.38777878e-16,  1.00000000e+00, -3.33066907e-16],
       [ 2.49800181e-16, -5.55111512e-17,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
m = np.array([[2, 2],
              [1, 3]])

np.linalg.eig(m)

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
A = np.eye(3).transpose()

#A = A + A[0]
A
#np.linalg.det(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
m = np.array([ [1, 4, 1],
               [1, 7, 2],
               [1, 6, 2]])

np.linalg.det(m)

1.0000000000000002